# Site Settings
theme: jekyll-theme-slate
title: THE ARCHIVES
description: >-
  Documenting the process of development, hardware exploration, and technical troubleshooting. A permanent record of the logic behind the magic.

# Build Settings
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed

# Navigation & Identity
url: "https://prasheelvarma.dev" # Replace when domain changes 
baseurl: ""